[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
#build-std = ["core", "compiler_builtins", "std", "panic_abort", "alloc"]

[build]
# Pretending to be Hermit so we can fool rust and get std :)
#target = "x86_64-unknown-hermit"
target = "x86_64-thek.json"
