[package]
name = "std"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.11", default-features = true, features = ['rustc-internal-api'] }
thek = { path = "../thek" }